apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'rocket-auth-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['rocket-auth-service:8080']
