global:
  scrape_interval: 15s  # Сколько времени между сбором метрик

scrape_configs:
  - job_name: 'spring-boot-actuator'
    metrics_path: '/actuator/prometheus'  # Путь для сбора метрик
    static_configs:
      - targets: ['host.docker.internal:8080']  # URL вашего приложения (используем host.docker.internal для доступа к приложению, работающему на хосте)
