apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-service-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocket-service-front
  template:
    metadata:
      labels:
        app: rocket-service-front
    spec:
      containers:
        - name: rocket-service-front
          image: flipperzer0/rocket-service-front:v1.0.1
          ports:
            - containerPort: 8088