apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rocket-service-front
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/rocket-gateway
  http:
    - match:
        - uri:
            prefix: /sign-up
      route:
        - destination:
            host: rocket-auth-service.default.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /login
      route:
        - destination:
            host: rocket-auth-service.default.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /actuator/prometheus
        route:
          - destination:
              host: rocket-auth-service.default.svc.cluster.local
              port:
                number: 8080
    - match:
        - uri:
            prefix: /grafana  # Все запросы, начинающиеся с /grafana
        route:
          - destination:
              host: grafana.monitoring.svc.cluster.local
              port:
                number: 3000
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: rocket-service-front.default.svc.cluster.local
            port:
              number: 80